sonar.organization=tropikhajma
sonar.projectKey=tropikhajma
sonar.projectName=OpenWrt Family Control
sonar.sources=luci-app-familycontrol
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.apk
